# Makefiles for Desinger-Open
Objects = Data_Bound.obj Data_DNA.obj Data_Geom.obj Data_Mesh.obj Data_Prob.obj \
		  Para.obj List.obj Mani.obj Math.obj SpanTree.obj Importer.obj TecPlot.obj Chimera.obj \
		  Exam_1_Platonic.obj Exam_2_Archimedean.obj Exam_3_Johnson.obj Exam_4_Catalan.obj \
		  Exam_5_Miscellaneous.obj Exam_8_Prism.obj \
		  3_Section.obj 1_Input.obj 2_ModGeo.obj 4_Basepair.obj 5_Route.obj 6_SeqDesign.obj 7_Output.obj \
		  Designer-Open.obj

#SRCS    = Data_Bound.f90 Data_DNA.f90 Data_Geom.f90 Data_Mesh.f90 Data_Prob.f90 \
#		  Para.f90 List.f90 Mani.f90 Math.f90 SpanTree.f90 Importer.f90 TecPlot.f90 Chimera.f90 \
#		  Exam_1_Platonic.f90 Exam_2_Archimedean.f90 Exam_3_Johnson.f90 Exam_4_Catalan.f90 \
#		  Exam_5_Miscellaneous.f90 Exam_8_Prism.f90 \
#		  3_Section.f90 1_Input.f90 2_ModGeo.f90 4_Basepair.f90 5_Route.f90 6_SeqDesign.f90 7_Output.f90 \
#		  Designer-Open.f90

Designer-Open: $(Objects)
	ifort -o Designer-Open $(Objects)

#$(Objects): $(SRCS)
#	ifort -c $(Objects) $(SRCS)

Data_Bound.obj : Data_Bound.f90
	ifort -c Data_Bound.obj Data_Bound.f90
Data_DNA.obj : Data_DNA.f90
	ifort -c Data_DNA.obj Data_DNA.f90
Data_Geom.obj : Data_Geom.f90
	ifort -c Data_Geom.obj Data_Geom.f90
Data_Mesh.obj : Data_Mesh.f90
	ifort -c Data_Mesh.obj Data_Mesh.f90
Data_Prob.obj : Data_Prob.f90
	ifort -c Data_Prob.obj Data_Prob.f90
Para.obj : Para.f90
	ifort -c Para.obj Para.f90
List.obj : List.f90
	ifort -c List.obj List.f90
Mani.obj : Mani.f90
	ifort -c Mani.obj Mani.f90
Math.obj : Math.f90
	ifort -c Math.obj Math.f90
SpanTree.obj : SpanTree.f90
	ifort -c SpanTree.obj SpanTree.f90
Importer.obj : Importer.f90
	ifort -c Importer.obj Importer.f90
TecPlot.obj : TecPlot.f90
	ifort -c TecPlot.obj TecPlot.f90
Chimera.obj : Chimera.f90
	ifort -c Chimera.obj Chimera.f90
Exam_1_Platonic.obj : Exam_1_Platonic.f90
	ifort -c Exam_1_Platonic.obj Exam_1_Platonic.f90
Exam_2_Archimedean.obj : Exam_2_Archimedean.f90
	ifort -c Exam_2_Archimedean.obj Exam_2_Archimedean.f90
Exam_3_Johnson.obj : Exam_3_Johnson.f90
	ifort -c Exam_3_Johnson.obj Exam_3_Johnson.f90
Exam_4_Catalan.obj : Exam_4_Catalan.f90
	ifort -c Exam_4_Catalan.obj Exam_4_Catalan.f90
Exam_5_Miscellaneous.obj : Exam_5_Miscellaneous.f90
	ifort -c Exam_5_Miscellaneous.obj Exam_5_Miscellaneous.f90
Exam_8_Prism.obj : Exam_8_Prism.f90
	ifort -c Exam_8_Prism.obj Exam_8_Prism.f90
3_Section.obj : 3_Section.f90
	ifort -c 3_Section.obj 3_Section.f90
1_Input.obj : 1_Input.f90
	ifort -c 1_Input.obj 1_Input.f90
2_ModGeo.obj : 2_ModGeo.f90
	ifort -c 2_ModGeo.obj 2_ModGeo.f90
4_Basepair.obj : 4_Basepair.f90
	ifort -c 4_Basepair.obj 4_Basepair.f90
5_Route.obj : 5_Route.f90
	ifort -c 5_Route.obj 5_Route.f90
6_SeqDesign.obj : 6_SeqDesign.f90
	ifort -c 6_SeqDesign.obj 6_SeqDesign.f90
7_Output.obj : 7_Output.f90
	ifort -c 7_Output.obj 7_Output.f90
Designer-Open.obj : Designer-Open.f90
	ifort -c Designer-Open.obj Designer-Open.f90